version: '3'

services:
  # https://hub.docker.com/_/mongo
  mongo:
    image: mongo
    container_name: demo-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: tz6xJxcz
    volumes:
      - ./mongodata:/data/db
    ports:
      - 51017:27017

  # https://hub.docker.com/_/mongo-express
  mongo-express:
    image: mongo-express
    container_name: demo-mongo-express
    restart: always
    ports:
      - 5101:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: tz6xJxcz
      ME_CONFIG_MONGODB_URL: mongodb://root:tz6xJxcz@mongo:27017/
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: tz6xJxcz