version: '3.8'

services:
  db1:
    image: mysql:latest
    container_name: mysql1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_username
      MYSQL_PASSWORD: your_password
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    ports:
      - "3306:3306"
    volumes:
      - mysql1-data:/var/lib/mysql

  db2:
    image: mysql:latest
    container_name: mysql2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_username
      MYSQL_PASSWORD: your_password
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    ports:
      - "3307:3306"  # Sử dụng cổng 3307 để tránh xung đột với cổng của db1
    volumes:
      - mysql2-data:/var/lib/mysql


volumes:
  mysql1-data:
  mysql2-data:
