version: '3.8'

services:
  master_mysql_1:
    image: mysql:5.7
    platform: linux/x86_64
    container_name: master_mysql_1
    ports:
      - 3308:3306
    volumes:
      - ./d1:/var/lib/mysql
      - './first-host.cnf:/etc/mysql/conf.d/mysql.cnf'
    environment:
      MYSQL_ROOT_PASSWORD: mypass

    networks:
      - replicanet

  master_mysql_2:
    image: mysql:5.7
    platform: linux/x86_64
    container_name: master_mysql_2
    ports:
      - 3309:3306
    volumes:
      - ./d2:/var/lib/mysql
      - './first-host.cnf:/etc/mysql/conf.d/mysql.cnf'
    environment:
      MYSQL_ROOT_PASSWORD: mypass

    networks:
      - replicanet


networks:
  replicanet:
    # Define network options if needed
