version: '3.8'

services:
  master_mariadb_1:
    image: mariadb:11.2.2
    platform: linux/x86_64
    container_name: master_mariadb_1
    ports:
      - 3308:3306
    volumes:
      - ./d1_mariadb1:/var/lib/mysql
      - './first-host.cnf:/etc/mysql/conf.d/mysql.cnf'
    environment:
      MYSQL_ROOT_PASSWORD: mypass

    networks:
      - replicanet

  master_mariadb_2:
    image: mariadb:11.2.2
    platform: linux/x86_64
    container_name: master_mariadb_2
    ports:
      - 3309:3306
    volumes:
      - ./d1_mariadb2:/var/lib/mysql
      - './second-host.cnf:/etc/mysql/conf.d/mysql.cnf'
    environment:
      MYSQL_ROOT_PASSWORD: mypass

    networks:
      - replicanet

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: phpmyadmin
  #   platform: linux/x86_64
  #   ports:
  #     - "8081:80"
  #   environment:
  #     PMA_HOST: database
  #     # PMA_PORT: ${MARIADB_PORT}
  #     PMA_ARBITRARY: 1
  #     UPLOAD_LIMIT: 300M
  #     # MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
  #   depends_on:
  #     database:
  #       condition: service_healthy
  #   restart: unless-stopped


networks:
  replicanet:
    # Define network options if needed
